{% set name = "circleclient" %}
{% set version = "0.1.6" %}
{% set checksum = "7aadf04294b5d8e9b668e749d8781c1aecfd022b1627349fa2d9473b3f4ce0b6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - requests

  run:
    - python
    - requests

test:
  imports:
    - circleclient

about:
  home: http://github.com/qba73/circleclient/
  license: MIT
  summary: Python client for CircleCI API

extra:
  recipe-maintainers:
    - jakirkham
