travis:
  secure:
    BINSTAR_TOKEN: d/hWJwwyESyaD9iRzN3XtcI6TeDbw0a9C/vK2Dmzfeh9KP2UyyWiMhSKN28OmaDeloii8CkLT/nP32exuwtGVvyNwFSm7BZP98WJQR+8d0GLFZa2LdG8mYpbS/cUkJD6CaHuM2uGdPIHq5Zg7YknJTk/4XIQY4G3mJ0eu2dCbs6Y4x3Em37hP6L7C873CQpcjx/BGazvozcxb7iGzQeLMJwNpM8d7oO7lRTApTJhhDNiBQWETnIMSsDDXMnL3z35QJfsGKjNzjETZCsZFYFsTPOGUrg80yKp5xwwmIXO1YtegWR9+JYOFdroRvrm2Nk6Yfcb1U+B9WonIAdGidkiOxPfkQnVK4GZPF3IZ7lX/dvj6T6jdPZr1LZaYOfSD5c8b0nvf8Ho0F4OyMERm66nPxsNKU7r7sOOh3XizIAE+BfePhOdVuDL9BGlqQ+yyQTavZS22vKRe9V+jZPZSmjq/3ZHxaNzfqtAl9+kKFvlP5BJs4X4D/vjx+dgJ5w8JblqmvN1wMbxMqlBOq9ub5xRuN+4hdMxj3PjWoDqST5TTP8Q4ZKHuOy6ri2UP51Ij3Mmr1WS338WKd+Zn+xZ1n9URbnwbKp6JNWyTek/fSNhmzY/NpE2BtUeKXfk4ZDpe+PbXujRSSKzbvoiV9/c2GlY6ErX1+ijNEdt5zSmA9Yu7cw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
