travis:
  secure:
    BINSTAR_TOKEN: jx5E82V48h1rufSIg4/rsviUgQDoq+VAwBoLBd5rfOS3+JehPv6Z0QcCJVjkL0seaFfaRVM/bOXQ4IGTGbaYxfqOhsgwDo88Lrp4Wde+QsAwyt+bMHf6IlyfAAiqVU4GdtHo6fsaQZ7zL7rJskAZowkMoLfR0+eQdVoI1XcIG+SlqCAORHoa8SswKFqNcGQzH2GEYSeOwT/YF/rEcQvRbXnadm0Hh2nIzMBkuvCBeeazyycPMiC8E8AwP/VOTmglF4xhgIKCB4ie8gxknX9B2y7O1a9Z0KFyz+xwRLT4OMqWG5HdOyWf568DX/fcezmd9E5+q7vlcEE2/HaxKkJhi50/+Chutia48bp0FLKxgONTboF2VtEkDlVH7xalL4oJpxGaoY7+80KF0dhCmX57MKGpFPP+EXdALkiUrdSQlNic3G7HU6Z4tj6BgzwN+5jb5Z9Lygh/yzMzjfjwEnOqFIYZsLos7hbwTUSL+mkttCD1eGYJB6rlDDiCqxMlXofHxz6/JrQHGasbp0cDB44VmcG7eXQyT9Qh8qtIjV/38gZgeqw6DK1a9MOoEmc0fzqqu2HthhsssTxk6dujffRiLy4eKxc2DzrqbBsFYTT6vQBJiIJp1ShQlDvOo9lOam2pNM6CfbpOmP3yEgtkQ3UqRjwWcd09I0Q3G8fIn7Crgpg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
